language: ruby
dist: bionic
rvm:
  - 2.6.5

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master
  - gh-pages
  - /.*/

cache: bundler

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
