language: ruby
dist: bionic
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master

cache: bundler

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true


notifications:
  email: false
