title: Khanifa
email: khanifa@test.com
description: >- 
  Build anything with Khanifa.
baseurl: "" 
url: "" 
twitter_username: anif_eka
instagram_username:  khanifaanip

theme: minima
plugins:
  - jekyll-feed
